### PR TITLE
feat:  Switch to more compliant interpreter

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@cscheid This includes the package registry changes to get it build on my machine - but the actual change is pretty minimal.

Note:  In my opinion the following test in quarto-cli:  https://github.com/quarto-dev/quarto-cli/blob/main/tests/docs/ojs/test-ojs-es-modules.qmd is incorrect, this is what I believe are valid examples:

`
import { f } from "./m1.ojs";  // where m1.ojs is observablehq compatible JS

m1 = import("./m1.js");  //  m1 is an JavaScript esm module
`

**Comment by cscheid** [comment]
That is not an incorrect test; that's desired behavior on our part. It's definitely not "pure" Observable, but it makes developing JS in HTML+observable pages a lot easier (especially since we also support typescript imports)

I'm honestly reluctant to merge this without understanding exactly what the impact is, especially since we now operate from a fork of the original OJS interpreter.

**Comment by cscheid** [comment]
I get it. Do you have examples in the wild where our import syntax breaks otherwise working code?

I'm very favorable towards making sure Quarto's OJS support is stable, and it appears to be the case that the library we depend on is now longer being maintained. But there's a few other issues I'd like to first understand. For example (and off the top of my head), our support allows observable-style imports from other .qmd notebooks,

```
import { someReactive } from "./another-file.qmd"
```

and this resolves correctly to getting the appropriate definitions from the HTML file.

**Comment by GordonSmith** [comment]
The compiler currently supports importing from the following "known" notebook formats:
* hosted on observablehq - `import { f } with { a as b } from "@gordon/myNotebook"`
* ojs - Just plain text with observable JS `import { f } with { a as b } from "./myNotebook.ojs"`
* omd - Similar to your qmd, but assumes markdown code sections with no specific tags `{xxx}` are also ojs `import { f } with { a as b } from "./myNotebook.omd"`
* ojsnb - JSON file which supports the ObservableHQ Notebook JSON format `import { f } with { a as b } from "./myNotebook.ojsnb"`

If importing a "qmd" file only ingests the ojs code sections, then I suspect renaming a xxx.qmd file to a xxx.omd would work today.

**Comment by cscheid** [comment]
Yes, so I think we unfortunately agree that these are not exactly compatible.

**Comment by cscheid** [comment]
I definitely appreciate your willingness to consider supporting our weird edge cases!

> My main concern would be IF you support `import { f } from "./mylib.qmd"` where f is NOT contained in a {ojs} block?

We don't, but as you will see, there's quite a few other features that we support which I don't think you would want to. I'm pointing them out not to ask that you incorporate them, but so that we can figure out how to solve it.

- we resolve paths differently depending on whether quarto pages are in a quarto website or book vs standalone
- we optionally bundle the `.js` and `.ts` imported files into the main page with `esbuild`
- we find file references in FileAttachment and capture them so that they're automatically copied over to the website output being produced.

Unfortunately, all of this functionality is split between `quarto-ojs-runtime` and code in https://github.com/quarto-dev/quarto-cli, specifically in the `src/execute/ojs/` subdirectory:

- https://github.com/quarto-dev/quarto-cli/blob/main/src/execute/ojs/compile.ts
- https://github.com/quarto-dev/quarto-cli/blob/main/src/execute/ojs/extract-resources.ts

We also have R, Python and Julia code that interacts with knitr and jupyter's HTML support and needs to find the OJS interpreter in order to add definitions to the runtime, to support the interaction between server-side interactive execution and client-side Javascript. The documentation has some R examples: https://quarto.org/docs/interactive/shiny/ There might be other places with dependencies as well that I might be missing!

**Comment by GordonSmith** [comment]
I don't think those bullet points are as scary as you might think - I suspect you will end up deleting a bunch of code...
> * we resolve paths differently depending on whether quarto pages are in a quarto website or book vs standalone
Do they maintain their relative paths or do they change - today you can initialize a baseUrl that the compiler will use when locating relative imports.

> * we optionally bundle the `.js` and `.ts` imported files into the main page with `esbuild`
I am not sure where in the pipeline esbuild lives (I have used it in some documentation generation code), but if its part of the static website generator then the compiler can be used to output plain js files similar to the ones you can download from observable, it can do this in a CLI mode as well.  At which point esbuild can bundle it and its imports.

> * we find file references in FileAttachment and capture them so that they're automatically copied over to the website output being produced.
The compiler already exposes a map of the found fileAttachements (assuming the source is a observablehq hosted site)

There is a slightly more detailed example here:  https://observablehq.com/@gordonsmith/observablehq-compiler

**Comment by cscheid** [comment]
> I suspect you will end up deleting a bunch of code

Well, to put it bluntly, if _you_ figure out how to make it all work in quarto and delete that code, then we'll merge! :)

But right now, we have our plates full with a lot of other work, and the PR doesn't add functionality that seems critically missing in quarto. It would be great to get it all under a single compiler, to be sure, but I'm not in a position to merge this until I'm positive everything that needs to work together works together.

**Comment by GordonSmith** [comment]
If there was a suite of unit tests I could do that, but I am quarto newb so wouldn't know all the use cases / edge cases...

**Comment by cscheid** [comment]
That's a totally fair criticism. We have a suite of tests but it's not nearly as complete as we'd like, because some of the behavior testing requires coordination across server and browser to a level that we haven't been able to easily automate :(

**Comment by GordonSmith** [comment]
Ok - I shall drop the hard sell!

Quick question, is it possible to add support for a new language via extensions (my day job is working on a big data platform, with its own functional language - hpccsystems.com)?

**Comment by cscheid** [comment]
Yes, that is definitely possible with Lua filters and extensions: https://quarto.org/docs/extensions/lua.html

**Pull request closed without merging**
